version: "3.8"

services:
  frontend:
    container_name: esb-frontend
    build: frontend
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    container_name: esb-postgres
    image: postgres:15
    command: -p 1234
    expose:
      - 1234
    env_file:
      - .env-deploy
    restart: unless-stopped

  backend:
    container_name: esb-backend
    build: backend
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env-deploy
    depends_on:
      - db
